### ISSUE TITLE
Test t/03scalar requires B::Cow; explodes if not loadable

### ISSUE THREAD

**Issue by kbulgrien** [garu/Clone#36] opened 2022-03-29 19:37 UTC
When a system does not have B::Cow, t/03scalar should handle the situation
without exploding.  It probably needs a test skip mechanism.

ok
t/03scalar.......Can't locate B/COW.pm in @INC (@INC contains: /csdi/src/sco507/perl/v5.8.8/Clone-0.45/blib/lib /csdi/src/sco507/perl/v5.8.8/Clone-0.45/blib/arch /usr/lib/perl5/5.8/i586-pc-sco3.2v5.0 /usr/lib/perl5/5.8 /usr/lib/perl5/site_perl/5.8/i586-pc-sco3.2v5.0 /usr/lib/perl5/site_perl/5.8 /usr/lib/perl5/site_perl/5.8 /usr/lib/perl5/sco_perl/5.8/i586-pc-sco3.2v5.0 /usr/lib/perl5/sco_perl/5.8 /usr/lib/perl5/sco_perl/5.8 .) at t/03scalar.t line 11.
BEGIN failed--compilation aborted at t/03scalar.t line 11.
dubious
        Test returned status 2 (wstat 512, 0x200)
t/04tie..........1..5

Seen in Clone-0.45.

**Comment by toddr** [comment] 2022-03-29 21:40
If you check the META files, test_requires and build_requires both specify B::Cow.

https://metacpan.org/dist/Clone

**Comment by atoomic** [comment] 2022-03-29 21:46
Indeed I think we should close this case as `By Design` you need `B::COW` to run tests 
view https://metacpan.org/release/ATOOMIC/Clone-0.45/source/META.json

Are you struggling to install B::COW?
thanks

**Comment by kbulgrien** [comment] 2022-03-30 05:25
Your call, but it seemed that a message could more directly indicate intent as in building a number of modules, have not generally seen this, but rather a more clear "warning" or "error" message.  My experience with perl is low, and it is hard to tell when the build system says, oh there's a problem, but then tests succeed, etc.  Yes, B::COW failed testing even though it indicated no missing required resources:

WARNING: MIN_PERL_VERSION is not a known parameter.
WARNING: LICENSE is not a known parameter.
Checking if your kit is complete...
Looks good
  ABSTRACT => q[B::COW additional B helpers to check COW status]
  AUTHOR => q[Nicolas R. <atoomic@cpan.org>]
  DISTNAME => q[B-COW]
  LICENSE => q[perl]
'LICENSE' is not a known MakeMaker parameter name.
  MIN_PERL_VERSION => q[5.008]
'MIN_PERL_VERSION' is not a known MakeMaker parameter name.
  NAME => q[B::COW]
  PREFIX => q[/csdi/src/sco507/perl/v5.8.8/dist/usr]
  PREREQ_PM => { Test::More=>q[0], File::Spec=>q[0], ExtUtils::MakeMaker=>q[0], Devel::Peek=>q[0] }
  VERSION => q[0.004]
  test => { TESTS=>q[t/*.t] }
Using PERL=/usr/bin/perl
Writing Makefile for B::COW

cp lib/B/COW.pm blib/lib/B/COW.pm
/usr/bin/perl /usr/lib/perl5/5.8/ExtUtils/xsubpp  -typemap /usr/lib/perl5/5.8/ExtUtils/typemap  COW.xs > COW.xsc && mv COW.xsc COW.c
Please specify prototyping behavior for COW.xs (see perlxs manual)
gcc -c   -DPERL_SCO -DPERL_SCO507 -DHAS_FPSETMASK -D_REENTRANT -DMAXPATHLEN=1024 -march=i586 -mcpu=i586 -O6 -fomit-frame-pointer   -DVERSION=\"0.004\" -DXS_VERSION=\"0.004\" -fPIC "-I/usr/lib/perl5/5.8/i586-pc-sco3.2v5.0/CORE"   COW.c
Running Mkbootstrap for B::COW ()
chmod 644 COW.bs
rm -f blib/arch/auto/B/COW/COW.so
gcc  -shared COW.o  -o blib/arch/auto/B/COW/COW.so      \
        \

chmod 755 blib/arch/auto/B/COW/COW.so
cp COW.bs blib/arch/auto/B/COW/COW.bs
chmod 644 blib/arch/auto/B/COW/COW.bs
lib/B/COW.pm:33: Unknown command paragraph "=encoding utf-8"
Manifying blib/man3/B::COW.3

PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(1, 'blib/lib', 'blib/arch')" t/*.t
t/00-load..............1..1
ok 1 - use B::COW;
ok
t/00-report-prereqs....1..1
#
# Versions for all modules listed in static metadata (including optional ones):
#
# === Configure Requires ===
#
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker  any 6.30
#
# === Test Requires ===
#
#     Module              Want Have
#     ------------------- ---- ----
#     Devel::Peek          any 1.03
#     ExtUtils::MakeMaker  any 6.30
#     File::Spec           any 3.12
#     Test::More           any 0.62
#
# === Test Recommends ===
#
#     Module         Want    Have
#     ---------- -------- -------
#     CPAN::Meta 2.120900 missing
#
# === Runtime Requires ===
#
#     Module Want Have
#     ------ ---- ----
#
ok 1
ok
t/01-basic.............Bareword "done_testing" not allowed while "strict subs" in use at t/01-basic.t line 69.
Execution of t/01-basic.t aborted due to compilation errors.
# Looks like your test died before it could output anything.
dubious
        Test returned status 255 (wstat 65280, 0xff00)
Failed Test  Stat Wstat Total Fail  Failed  List of Failed
-------------------------------------------------------------------------------
t/01-basic.t  255 65280    ??   ??       %  ??
Failed 1/3 test scripts, 66.67% okay. 0/2 subtests failed, 100.00% okay.
make: *** [test_dynamic] Error 255

Now that that is written, and even though "CPAN::Meta" is only "Recommends", I
have built and installed direct and indirect dependencies of CPAN-Meta as
best I know how:
  version >= 0.88
   JSON-PP >= 2.273
  CPAN-Meta-Requirements >= 2.12
    Test-Simple >= 1.3
      parent >= 0.221
      File-Path >= 2.06
    File-Temp >= 0.19
 CPAN-Meta-YAML >= 0.011
 CPAN-Meta >= 2.1209
Now B::COW doesn't complain and passes all tests.

I remain confused by the idea that a crash is good enough vs. a clear message.
Even in the B::COW case, the clear message was that CPAN-Meta wasn't a
requirement, yet the tests didn't do anything but cast doubt on the build by
"blowing up" unless the "recommended" configuration was used.  I had to
build supposedly not necessary  stuff to meet a recommended configuration
just to see it was actually more of a requirement.  Is simple enough to emit an
"is required" message if a module doesn't load.  Not being a perl guru, even
I've figured that out, and can tell the user in plain language that its not going
to work without such and such, vs. spewing shrapnel everywhere.  LOL.  But, its
your call, I'll move on without worrying further about it.

**Comment by garu** [comment] 2022-03-30 13:55
Hi @kbulgrien! First of all, thank you for taking the time to submit this report - we really appreciate you not only installing and using it, but also trying to improve the overall quality of both Clone and B::COW for other developers.

It is still a bit hard to say for sure, but this _looks_ like a problem with your working perl toolchain (e.g. the environment, modules and perl versions used to install Clone), not Clone itself. Either way, I'm confident we can do better!

For instance, I saw from your original report that you're using perl 5.8.8, is that correct? And what operating system are you using? I'm guessing SCO OpenServer 5.0.7, is that correct?

In order for us to be able to reproduce this, would you kindly show us your "perl -V" output? If not, just confirming it is indeed perl 5.8.8, the operating system it is running under, and whether it's system perl or a custom built perl (and if so, which flags you used to build it) will already be a huge help.

For (our) future reference, your original installation had ExtUtils::MakeMaker 6.30 and Test::More 0.62, and installing CPAN::Meta got Test-Simple 1.3.

Thanks again!

**Comment by atoomic** [comment] 2022-03-30 14:48
Indeed additionally we can consider add some `skip` in tests if the package is missing
But I think this would only be useful when trying to install it manually without dependencies

**Comment by atoomic** [comment] 2022-03-30 16:09
we need something similar to what s done by `t/cow.t` 
```perl
BEGIN {

    # Travis issue on 5.8.8 (maybe the module is too recent...)
    my $load_B_COW = eval { require B::COW; B::COW->import(q/:all/); 1 };

    if ( $@ || !$load_B_COW ) {
        plan skip_all => 'This test requires B::COW to run.';
    }
    if ( !B::COW::can_cow() ) {
        plan skip_all => 'This test is only designed to work on Perl Versions supporting COW';
    }
}
```

**Comment by kbulgrien** [comment] 2022-03-30 20:35
> Hi @kbulgrien! First of all, thank you for taking the time to submit this report - we really appreciate you not only installing and using it, but also trying to improve the overall quality of both Clone and B::COW for other developers.

You're welcome.  Hopes are not to be a pedantic pain for no good.

> It is still a bit hard to say for sure, but this _looks_ like a problem with your working perl toolchain (e.g. the environment, modules and perl versions used to install Clone), not Clone itself. Either way, I'm confident we can do better!
> 
> For instance, I saw from your original report that you're using perl 5.8.8, is that correct? And what operating system are you using? I'm guessing SCO OpenServer 5.0.7, is that correct?

Ugh, you want me to admit that, eh?  Yes, these details are true indeed.  In SCO nomenclature, my system is configured with the following packages.  I have been careful to not damage the original install.  The build procedure takes extraordinary care to restore the system to its original state after packaging new components.  I say this primarily to indicate that if there is a system problem, it probably was with the original vendor configuration.

```
          FSUpthreads - POSIX 1003.1c threads implementation (ver 3.14)
          GNU Development Tools (ver 5.0.7Kj)
          GNU Development Tools (ver 5.0.7g)
          Java 2 1.3.1_22 Runtime Environment (ver 1.3.1Va)
          Java 2 1.3.1_22 Software Development Kit (ver 1.3.1Va)
          Java 2 1.4.2_18 Runtime Environment (ver 1.4.2Ra)
          Java 2 1.4.2_18 Software Development Kit (ver 1.4.2Ra)
          SCO OpenServer Development System (ver 5.2.0Aa)
          SCO OpenServer Enterprise System (ver 5.0.7Hw)
          SCO OpenServer Release 5.0.7 Maintenance Pack 5 (ver 1.0.0Mc)

```
When I first build a module, I first remove all other modules I have already built so I can evaluate the requirements against a base OS configuration.  I then document what needs to be installed to optimally build/test the new module.  I then build / install dependencies as needed (the latest versions in CPAN if possible).  Very few CPAN modules have required me to build an older version, but I have run amuck of some constraints related to the age of gcc, etc.

> In order for us to be able to reproduce this, would you kindly show us your "perl -V" output? If not, just confirming it is indeed perl 5.8.8, the operating system it is running under, and whether it's system perl or a custom built perl (and if so, which flags you used to build it) will already be a huge help.

```
$ perl -V
Summary of my perl5 (revision 5 version 8 subversion 8) configuration:
  Platform:
    osname=sco, osvers=5.0.7, archname=i586-pc-sco3.2v5.0
    uname='sco_sv keats 3.2 5.0.7 i386 '
    config_args='-Dcc=gcc -Dprefix=/usr -Dmake=gmake -Dhintfile=sco_5_0_7.sh -Dmksymlinks -d -e -s'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=undef usesocks=undef
    use64bitint=define use64bitall=undef uselongdouble=define
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-DPERL_SCO -DPERL_SCO507 -DHAS_FPSETMASK -D_REENTRANT -DMAXPATHLEN=1024',
    optimize='-march=i586 -mcpu=i586 -O6 -fomit-frame-pointer',
    cppflags='-DPERL_SCO -DPERL_SCO507 -DHAS_FPSETMASK -D_REENTRANT -DMAXPATHLEN=1024 -fno-strict-aliasing -pipe'
    ccversion='', gccversion='2.95.3 20030528 (SCO/p7)', gccosandvers='sco3.2v5.0'
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long long', ivsize=8, nvtype='long double', nvsize=12, Off_t='off_t', lseeksize=4
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =''
    libpth=/usr/gnu/lib /usr/lib /lib
    libs=-lsocket -lndbm -lgdbm -ldb -lm -lcrypt -lc -lprot
    perllibs=-lsocket -lm -lcrypt -lc -lprot
    libc=, so=so, useshrplib=true, libperl=libperl.so
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-Bexport'
    cccdlflags='-fPIC', lddlflags='-shared'


Characteristics of this binary (from libperl):
  Compile-time options: USE_64_BIT_INT USE_LONG_DOUBLE USE_PERLIO
  Built under sco
  Compiled at Jun 22 2006 10:41:56
  @INC:
    /usr/lib/perl5/5.8/i586-pc-sco3.2v5.0
    /usr/lib/perl5/5.8
    /usr/lib/perl5/site_perl/5.8/i586-pc-sco3.2v5.0
    /usr/lib/perl5/site_perl/5.8
    /usr/lib/perl5/site_perl/5.8
    /usr/lib/perl5/sco_perl/5.8/i586-pc-sco3.2v5.0
    /usr/lib/perl5/sco_perl/5.8
    /usr/lib/perl5/sco_perl/5.8
    .
``` 

> For (our) future reference, your original installation had ExtUtils::MakeMaker 6.30 and Test::More 0.62, and installing CPAN::Meta got Test-Simple 1.3.
> 
> Thanks again!

**Comment by atoomic** [comment] 2022-03-30 20:39
I've submitted a fix and updated the CI workflow to detect such issues in the future 
view: https://github.com/atoomic/Clone/commit/0dd48d3e9bac7b5481d858781d80108777ba9a83

**Comment by kbulgrien** [comment] 2022-03-30 20:52
> I've submitted a fix and updated the CI workflow to detect such issues in the future view: [atoomic@0dd48d3](https://github.com/atoomic/Clone/commit/0dd48d3e9bac7b5481d858781d80108777ba9a83)

Would you care for a similar report for your B::COW or shall I leave it alone?

**Comment by garu** [comment] 2022-03-30 21:09
@atoomic thank you! but do you think it should `exit`? I thought we could toggle something like `$has_cow` and skip only that part of the tests, not all of them (if possible).

**Comment by kbulgrien** [comment] 2022-03-30 21:17
Excuse my ignorance, but perhaps t/07magic.t has an example of how it is done another way?  I think the SKIP { } structure may be relevant, however, as I have not written a perl module myself, perhaps it is not relevant.

**Comment by atoomic** [comment] 2022-03-30 21:50
@kbulgrien regarding B::COW, please report a bug so I can understand and investigate the issue

@garu Indeed I can improve the test to only skip when needed
was trying to provide a quick fixup let me improve it...

**Comment by atoomic** [comment] 2022-03-30 21:54
@garu https://github.com/atoomic/Clone/commit/7d9c699e962494fcdf7fd0c929c86195b29cb40f is now providing a better skip logic :-) 
just passed the no-cow test workflow

**Comment by garu** [comment] 2022-03-31 04:19
Thank you, @atoomic! Looks great now. Could you make a PR for this so we can merge and release a new version? I see the commit inside #35 but I think it should be separate from it, since it's regarding a travis update, not a test improvement.

**Comment by atoomic** [comment] 2022-03-31 04:29
I can split and provide an isolated PR but at the end this will be the same commit
If we merge the improved CI we have it for free as an extra commit

**Closed** 2022-03-31 04:47 UTC

**Comment by garu** [comment] 2022-03-31 04:50
@atoomic Thank you! It's merged.

@kbulgrien When you have the time, could you download and test a brand new Clone installation from this repository into your system to see if the issue is resolved and/or if there are any pending concerns or areas of improvement? Thank you!

**Comment by atoomic** [comment] 2022-03-31 05:03
We can do a release with that minor change
